# Generated by Django 5.1.4 on 2025-01-08 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empid', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('salary', models.IntegerField()),
                ('location', models.CharField(max_length=20)),
                ('designation', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
